name: One Ham Army
description: Hermann Vocke on software development, technology and random stuff
url: http://www.onehamarmy.com
markdown: kramdown
include: ['.htaccess']
highlighter: pygments

paginate: 5
paginate_path: "/blog/page:num"
